parameters:
  - name: platform
    type: string
  - name: configuration
    type: string
  - name: prefast
    type: string

steps:
  - template: checkout.yml

  - task: PkgESSetupBuild@12
    displayName: PkgES build setup
    inputs:
      useDfs: false
      productName: XboxLiveTraceAnalyzer
      branchVersion: true
      extSync: true

  - task: PoliCheck@1
    displayName: Run PoliCheck

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.8'
    inputs:
      versionSpec: 5.8

  - task: NuGetAuthenticate@0

  # Install NuGet dependencies. The GUID below is the NuGetCommand
  # Refs:
  # - https://developercommunity.visualstudio.com/t/vsts-yaml-build-failure-the-task-name-nugetcommand/288534
  # - https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget
  - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2
    displayName: NuGet restore
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      packDestination: '$(Build.ArtifactStagingDirectory)\External\Packages'

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 2.1.x
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 3.1.x
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: BatchScript@1
    displayName: preCompileScript.cmd
    inputs:
      filename: Utilities/Pipelines/Scripts/preCompileScript.cmd
      modifyEnvironment: false
    
  # Build the Visual Studio 17 solution.
  # Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build
  - task: VSBuild@1
    displayName: Build ${{ parameters.platform }}+${{ parameters.configuration }} Solution
    inputs:
      solution: 'Source\XBLTraceAnalyzer.sln'
      vsVersion: 15.0
      msbuildArchitecture: x64
      platform: ${{ parameters.platform }}
      configuration: ${{ parameters.configuration }}
      createLogFile: true
      logProjectEvents: true
      logFileVerbosity: 'diagnostic'
      
  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: Component Detection

  - task: BatchScript@1
    displayName: postBuildScript.cmd
    inputs:
      filename: 'Utilities/Pipelines/Scripts/postBuildScript.cmd'

  #Install Node.js. Required for Package ES SDL Guardian step.
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'

  - task: PkgESVPack@12
    displayName: 'Package ES - VPack'
    inputs:
      sourceDirectory: '$(Pipeline.Workspace)\b\TraceAnalyzer\Tools-VPack'
      description: 'TraceAnalyzer.$(CONFIGURATION)'
      pushPkgName: 'TraceAnalyzer.$(CONFIGURATION)'
    env:
      PAT: $(PAT-XboxADO)

  - task: CmdLine@1
    displayName: postBuildScriptVPack.cmd
    inputs:
      filename: 'Utilities/Pipelines/Scripts/postBuildScriptVPack.cmd'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact'
    inputs:
      targetPath: '$(Pipeline.Workspace)\b\TraceAnalyzer'
      artifact: 'Trace_Analyzer_PipelineArtifacts_$(CONFIGURATION)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact VPack'
    inputs:
      targetPath: '$(Pipeline.Workspace)\b\TraceAnalyzer\Tools-VPack'
      artifact: 'Trace_Analyzer_PipelineArtifacts_VPack_$(CONFIGURATION)'
