# CI trigger. Fires on merges to specific branches.
# Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git#ci-triggers

trigger:
  branches:
    include:
      - main
      - feature/*
    exclude:
      - hotfix/*

# Name builds with the definition name, date, and build-count-for-that-day. For
# example, "BuildDefName_20210214.1".
# Refs:
# - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number
# - https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables

name: $(Build.DefinitionName)_$(date:yyMMdd).$(rev:r)

resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: templates_onebranch
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

jobs:

  ####################
  # Visual Studio 2019
  ####################

  - job: Win32Vs19Build
    displayName: XblTraceAnalyzer Win32 VS2019 Build
    pool:
      name: xbl-1es-vs2019-pool
    timeoutInMinutes: 180
    strategy:
      matrix:
        AnyCPU_Debug:
          Platform: Any CPU
          Configuration: Debug
          Prefast: Disable
        AnyCPU_Release:
          Platform: Any CPU
          Configuration: Release
          Prefast: Disable
    steps:
      - template: Tasks/vs2019-build.yml
        parameters:
          platform: $(Platform)
          configuration: $(Configuration)
          prefast: $(Prefast)
